# permissions for end users to view subnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnamespace-viewer-role
rules:
- apiGroups:
  - dana.github.com/Dana-Team/SNS
  resources:
  - subnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dana.github.com/Dana-Team/SNS
  resources:
  - subnamespaces/status
  verbs:
  - get
