# permissions for end users to edit subnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnamespace-editor-role
rules:
- apiGroups:
  - dana.github.com/Dana-Team/SNS
  resources:
  - subnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.github.com/Dana-Team/SNS
  resources:
  - subnamespaces/status
  verbs:
  - get
